name: Build OpenWrt 25.12

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync unzip zlib1g-dev libc6-dev-i386 xz-utils curl wget

    - name: Clone OpenWrt 25.12 source
      run: |
        # 锁定官方最新 25.12 分支
        git clone -b openwrt-25.12 --depth 1 https://github.com/openwrt/openwrt.git openwrt

    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        cp ../diy.sh ./
        chmod +x diy.sh
        ./diy.sh
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        cp .config openwrt/.config
        cd openwrt
        make defconfig

    - name: Download package
      working-directory: ./openwrt
      run: make download -j8

    - name: Compile the firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread compile"
        # 强制将 CI 变量设为 false，防止 Rust 1.90.0 编译脚本崩溃
        export CI=false
        make -j$(nproc) || make -j1 V=s

    - name: Upload firmware directory
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_25.12_Firmware
        path: openwrt/bin/targets/*/*/*.*
